### ISSUE TITLE
Sorry, I can't build it.

### ISSUE THREAD

**Issue by tuchangwei** [qutheory/vapor-news#1]
Hi,

I am a beginner to use vapor, when I built your project, I got the following error. I use Xcode8 beta2. Is it caused by my swift environment is different with yours?

![image](https://cloud.githubusercontent.com/assets/2604045/16898100/bfd3d81e-4bfb-11e6-8df6-afa901f962ed.png)

**Comment by tannernelson** [comment]
This can be solved by removing the `Deploy` folder or adding it to the list of excludes in `Package.swift`
